export const ES_ISO_PROVINCES:any = {
  C: "A Coruña",
  VI: "Álava",
  AB: "Albacete",
  A: "Alicante",
  AL: "Almería",
  O: "Asturias",
  AV: "Ávila",
  BA: "Badajoz",
  B: "Barcelona",
  BI: "Bizkaia",
  BU: "Burgos",
  CC: "Cáceres",
  CA: "Cádiz",
  S: "Cantabria",
  CS: "Castellón",
  CR: "Ciudad Real",
  CO: "Córdoba",
  CU: "Cuenca",
  SS: "Gipuzkoa",
  GI: "Girona",
  GR: "Granada",
  GU: "Guadalajara",
  H: "Huelva",
  HU: "Huesca",
  PM: "Illes Balears",
  J: "Jaén",
  LO: "La Rioja",
  GC: "Las Palmas",
  LE: "León",
  L: "Lleida",
  LU: "Lugo",
  M: "Madrid",
  MA: "Málaga",
  MU: "Murcia",
  NA: "Navarra",
  OR: "Ourense",
  P: "Palencia",
  PO: "Pontevedra",
  SA: "Salamanca",
  TF: "Santa Cruz de Tenerife",
  SG: "Segovia",
  SE: "Sevilla",
  SO: "Soria",
  T: "Tarragona",
  TE: "Teruel",
  TO: "Toledo",
  V: "Valencia",
  VA: "Valladolid",
  ZA: "Zamora",
  Z: "Zaragoza"
}
